# Generated by Django 3.2.7 on 2021-09-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_auto_20210919_2018'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='contenido',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='subtitle',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
